name: Packaging

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency: 
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        python -m poetry install
    - name: Create pyinstaller executable
      run: |
        python -m poetry run pyinstaller pkg/pyinstaller/yastr.spec
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}
        path: |
          dist/yastr
          dist/yastr.*
        retention-days: 1
